apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 20
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 20
