apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-site-content
  labels:
    app: nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  index.html: |-
    {{- .Files.Get "files/site.html" | nindent 4 }}
